apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Presence-Service
  description: Device xagent could post presence data on startup or by demand.
  annotations:
    pagerduty.com/integration-key: <sample-service-integration-key>
  tags:
    - java
    - xcloud
    - presence
  links:
    - url: https://arlo.com
      title: Main resource
      icon: dashboard
      type: admin-dashboard
spec:
  owner: Xcloud
  lifecycle: dev
  type: service
  system: xcloud
  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Fill in the repo details
      required:
        - github_repo_name
        - github_repo_description
        - github_repo_owner
      properties:
        github_repo_name:
          title: Repository Location
          type: string
          description: Name the new repository that you want to create
        github_repo_description:
          title: Description of the app being scaffolded
          type: string
          description: Description of the app being scaffolded
        github_repo_owner:
          title: Choose an Owner for the Service
          type: string
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken       
  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: trigger
      name: Provision a New Application Pattern
      action: trigger:harness-custom-pipeline
      input:
        url: "https://app.harness.io/ng/account/IFG41DWvSnaRLOVNB2uesg/module/idp-admin/orgs/idp/projects/SelfService_Onboarding/pipelines/OnboardAppPipeline/pipeline-studio?storeType=INLINE"
        inputset:
          github_repo_name: ${{ parameters.github_repo_name }}
          github_repo_description: ${{ parameters.github_repo_description }}
          github_repo_owner: ${{ parameters.github_repo_owner }}
        apikey: ${{ parameters.token }}
    # The final step is to register our new component in the catalog.

  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
